<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Compile Remove="NewFolder2\**" />
    <Compile Remove="NewFolder3\**" />
    <Compile Remove="NewFolder4\**" />
    <Compile Remove="NewFolder5\**" />
    <Compile Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder2\**" />
    <EmbeddedResource Remove="NewFolder3\**" />
    <EmbeddedResource Remove="NewFolder4\**" />
    <EmbeddedResource Remove="NewFolder5\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder1\**" />
    <None Remove="NewFolder2\**" />
    <None Remove="NewFolder3\**" />
    <None Remove="NewFolder4\**" />
    <None Remove="NewFolder5\**" />
    <None Remove="NewFolder\**" />
    <Page Remove="NewFolder1\**" />
    <Page Remove="NewFolder2\**" />
    <Page Remove="NewFolder3\**" />
    <Page Remove="NewFolder4\**" />
    <Page Remove="NewFolder5\**" />
    <Page Remove="NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AnaPencere.xaml.cs" />
    <Compile Remove="Views\BildirimlerView.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="Image1.png" />
    <None Remove="stokk.jpg" />
    <None Remove="Views\stokk.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="AnaPencere.xaml" />
    <Page Remove="Views\BildirimlerView.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\stokk.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="stokk.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\LoginWindow.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
