// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokYonetimSistemi.Data;

#nullable disable

namespace StokYonetimSistemi.Migrations
{
    [DbContext(typeof(StokYonetimContext))]
    [Migration("20250528113257_DecimalPrecisionEklendi")]
    partial class DecimalPrecisionEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StokYonetimSistemi.Models.Bildirim", b =>
                {
                    b.Property<int>("BildirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimID"));

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("BildirimID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Bildirim");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Depo", b =>
                {
                    b.Property<int>("DepoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepoID"));

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DepoAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SorumluPersonelID")
                        .HasColumnType("int");

                    b.HasKey("DepoID");

                    b.ToTable("Depo");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Etiket", b =>
                {
                    b.Property<int>("EtiketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtiketID"));

                    b.Property<string>("EtiketAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EtiketID");

                    b.ToTable("Etiket");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Fatura", b =>
                {
                    b.Property<int>("FaturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaID"));

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("SiparisID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("FaturaID");

                    b.HasIndex("SiparisID");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.FaturaDetay", b =>
                {
                    b.Property<int>("FaturaDetayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaDetayID"));

                    b.Property<int>("FaturaID")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("FaturaDetayID");

                    b.HasIndex("FaturaID");

                    b.HasIndex("UrunID");

                    b.ToTable("FaturaDetay");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.FavoriUrun", b =>
                {
                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("KullaniciID", "UrunID");

                    b.HasIndex("UrunID");

                    b.ToTable("FavoriUrunler");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("RolID");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("IslemTuru")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("TabloAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Zaman")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.LoginLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<bool>("Basarili")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GirisZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("LoginLog");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.RaporLog", b =>
                {
                    b.Property<int>("RaporLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaporLogID"));

                    b.Property<DateTime>("AlinmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("RaporAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RaporLogID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("RaporLog");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.RaporSablonu", b =>
                {
                    b.Property<int>("RaporID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaporID"));

                    b.Property<int>("OlusturanKullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("RaporAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SorguMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("RaporID");

                    b.HasIndex("OlusturanKullaniciID");

                    b.ToTable("RaporSablonu");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolID");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisID"));

                    b.Property<string>("Durum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("TedarikciID")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("SiparisID");

                    b.HasIndex("TedarikciID");

                    b.ToTable("Siparis");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.SiparisDetay", b =>
                {
                    b.Property<int>("SiparisDetayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisDetayID"));

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("SiparisID")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("SiparisDetayID");

                    b.HasIndex("SiparisID");

                    b.HasIndex("UrunID");

                    b.ToTable("SiparisDetay");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Stok", b =>
                {
                    b.Property<int>("StokID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StokID"));

                    b.Property<int>("DepoID")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("StokID");

                    b.HasIndex("DepoID");

                    b.HasIndex("UrunID");

                    b.ToTable("Stok");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.StokHareketi", b =>
                {
                    b.Property<int>("HareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HareketID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DepoID")
                        .HasColumnType("int");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("HareketID");

                    b.HasIndex("DepoID");

                    b.HasIndex("UrunID");

                    b.ToTable("StokHareketi");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Tedarikci", b =>
                {
                    b.Property<int>("TedarikciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TedarikciID"));

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Eposta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TedarikciID");

                    b.ToTable("Tedarikci");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Birim")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int?>("KritikStok")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("UrunID");

                    b.HasIndex("KategoriID");

                    b.ToTable("Urun");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.UrunEtiket", b =>
                {
                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.Property<int>("EtiketID")
                        .HasColumnType("int");

                    b.HasKey("UrunID", "EtiketID");

                    b.HasIndex("EtiketID");

                    b.ToTable("UrunEtiket");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Yetki", b =>
                {
                    b.Property<int>("YetkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YetkiID"));

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("TabloAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YetkiTuru")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("YetkiID");

                    b.HasIndex("RolID");

                    b.ToTable("Yetki");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.ZamanlanmisIslem", b =>
                {
                    b.Property<int>("IslemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("CronIfadesi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IslemAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IslemID");

                    b.ToTable("ZamanlanmisIslem");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Bildirim", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Fatura", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.FaturaDetay", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokYonetimSistemi.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.FavoriUrun", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokYonetimSistemi.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Kullanici", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Log", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.LoginLog", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.RaporLog", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.RaporSablonu", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Siparis", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Tedarikci", "Tedarikci")
                        .WithMany()
                        .HasForeignKey("TedarikciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tedarikci");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.SiparisDetay", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokYonetimSistemi.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Stok", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokYonetimSistemi.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.StokHareketi", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokYonetimSistemi.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Urun", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriID");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.UrunEtiket", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Etiket", "Etiket")
                        .WithMany()
                        .HasForeignKey("EtiketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokYonetimSistemi.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiket");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("StokYonetimSistemi.Models.Yetki", b =>
                {
                    b.HasOne("StokYonetimSistemi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
